
export type Language = 'en' | 'ar' | 'ku';

export interface PatientImage {
  id: string;
  url: string;
  name: string;
  date: string;
  driveFileId?: string; // ID of the file on Google Drive
}

export interface Theme {
  id: string;
  nameEn: string;
  nameAr: string;
  nameKu: string;
  type: 'light' | 'dark';
  colors: {
    primary: string;
    secondary: string;
    bg: string;
  };
}

export interface Doctor {
  id: string;
  name: string;
  username?: string; 
  password?: string; 
  rxBackgroundImage?: string; 
  dashboardPin?: string;
}

export interface Secretary {
  id: string;
  name: string;
  username: string;
  password: string;
}

export interface Appointment {
  id: string;
  patientId: string;
  patientName: string;
  date: string;
  time: string;
  duration?: number;
  treatmentType?: string;
  sessionNumber?: number;
  notes?: string;
  status: 'scheduled' | 'completed' | 'cancelled' | 'noshow';
}

export interface Payment {
  id: string;
  date: string;
  amount: number;
  description: string;
  type: 'payment' | 'charge';
}

export interface ToothSurfaces {
  top: string;
  bottom: string;
  left: string;
  right: string;
  center: string;
}

export interface ToothNote {
  text: string;
  align: 'left' | 'center' | 'right';
  fontSize: number;
  textColor: string;
  bgColor: string;
}

export interface Tooth {
  id: number; 
  status: 'healthy' | 'decay' | 'filled' | 'missing' | 'crown' | 'rct' | 'extraction' | 'bridge' | 'veneer';
  surfaces?: ToothSurfaces;
  notes?: string;
  specialNote?: ToothNote;
}

export interface RootCanalEntry {
  id: string;
  toothNumber: string;
  canalName: string;
  length: string;
  date: string;
}

export interface TreatmentSession {
  id: string;
  date: string;
  description: string;
}

export interface Medication {
  id: string;
  name: string;
  dose: string;
  frequency: string;
  form: string;
  notes?: string;
}

export interface Prescription {
  id: string;
  date: string;
  medications: Medication[];
  notes?: string;
}

export interface SupplyItem {
  id: string;
  name: string;
  quantity: number;
  price?: number;
}

export interface InventoryItem {
  id: string;
  name: string;
  quantity: number;
  minQuantity: number;
  price?: number;
  expiryDate?: string;
  color: string;
}

export interface ExpenseItem {
  id: string;
  name: string;
  quantity: number;
  price: number;
  date: string;
  uid?: string;
}

export interface DocumentTemplate {
  id: string;
  title: string;
  text: string;
}

export type PatientCategory = 'diagnosis' | 'rct' | 'implant' | 'crown' | 'surgery' | 'ortho' | 'filling' | 'cleaning' | 'smile' | 'whitening' | 'other';

export interface MedicalConditionItem {
  id: string;
  active: boolean;
}

export interface PatientQueryAnswer {
  questionId: string;
  answerId: string;
}

export interface Patient {
  id: string;
  name: string;
  phone: string;
  phoneCode?: string;
  age: number;
  gender: 'male' | 'female';
  category?: PatientCategory;
  address?: string;
  medicalHistory: string;
  structuredMedicalHistory?: MedicalConditionItem[];
  patientQueries?: PatientQueryAnswer[];
  dentalHistoryNotes?: string;
  status: 'active' | 'finished' | 'pending' | 'discontinued'; 
  doctorId: string;
  createdAt: string;
  teeth: Record<number, Tooth>;
  headMap?: Record<string, string>;
  bodyMap?: Record<string, string>;
  appointments: Appointment[];
  payments: Payment[];
  notes: string;
  rootCanals: RootCanalEntry[];
  treatmentSessions: TreatmentSession[];
  prescriptions: Prescription[];
  images?: PatientImage[]; 
  rctDrawing?: string; // local base64
  rctDrawingDriveId?: string; // cloud status
  profilePicture?: string; // base64 local
  profilePictureDriveId?: string; // drive ID
}

export interface TodoItem {
  id: string;
  text: string;
  done: boolean;
}

export interface MemoStyle {
  direction: 'ltr' | 'rtl';
  fontSize: number;
  textColor: string;
  isItalic: boolean;
  titleFontSize: number;
  titleColor: string;
}

export interface Memo {
  id: string;
  title: string;
  content: string;
  type?: 'text' | 'todo';
  todos?: TodoItem[];
  color: string;
  date: string;
  style?: MemoStyle;
}

export type LabOrderStatus = 'in_progress' | 'ready' | 'received' | 'cancelled';

export interface LabOrder {
  id: string;
  patientId: string;
  patientName: string;
  labName: string;
  workType: string;
  toothCount?: number;
  toothNumbers?: string;
  shade?: string;
  price?: number;
  sentDate: string;
  status: LabOrderStatus;
  notes?: string;
}

export interface TextStyleConfig {
  fontSize: number;
  color: string;
  isBold: boolean;
  isItalic: boolean;
}

export interface DocumentSettings {
    text: string;
    fontSize: number;
    align: 'left' | 'center' | 'right';
    topMargin: number;
    backgroundImage?: string;
}

export interface ClinicData {
  clinicName: string;
  doctors: Doctor[];
  secretaries: Secretary[];
  patients: Patient[];
  guestAppointments: Appointment[];
  memos: Memo[];
  supplies: SupplyItem[];
  inventory: InventoryItem[];
  expenses: ExpenseItem[];
  medications: Medication[];
  documentTemplates: DocumentTemplate[];
  labOrders: LabOrder[];
  labs: string[];
  settings: {
    language: Language;
    theme: 'light' | 'dark';
    currency: string;
    appScale: number;
    defaultCountryCode: string;
    isLoggedIn: boolean;
    rxBackgroundImage?: string;
    consentBackgroundImage?: string;
    instructionsBackgroundImage?: string;
    clinicPhone?: string;
    dashboardEnabled?: boolean;
    dashboardPin?: string;
    adminPassword?: string;
    googleDriveLinked?: boolean; 
    googleDriveRootId?: string; // The ID of Dentro_Clinic_Files folder
    rxTemplate?: {
        rxSymbol: TextStyleConfig;
        medications: TextStyleConfig;
        topMargin?: number;
    };
    consentSettings?: DocumentSettings;
    instructionSettings?: DocumentSettings;
  };
  lastUpdated: number;
  lastSynced?: string;
}

export const INITIAL_DATA: ClinicData = {
  clinicName: "",
  doctors: [],
  secretaries: [],
  patients: [],
  guestAppointments: [],
  memos: [],
  supplies: [],
  inventory: [],
  expenses: [],
  medications: [
    { id: '1', name: 'Amoxicillin', dose: '500mg', frequency: '3 times daily', form: 'cap' },
    { id: '2', name: 'Ibuprofen', dose: '400mg', frequency: 'When needed', form: 'tab', notes: 'After food' },
    // Fix: changed 'font' to 'form' to comply with Medication interface
    { id: '3', name: 'Paracetamol', dose: '500mg', frequency: 'Every 6 hours', form: 'tab' },
    // Fix: changed 'font' to 'form' to comply with Medication interface
    { id: '4', name: 'Metronidazole', dose: '500mg', frequency: '3 times daily', form: 'tab' },
    { id: '5', name: 'Augmentin', dose: '625mg', frequency: '2 times daily', form: 'tab' },
  ],
  documentTemplates: [],
  labOrders: [],
  labs: ['Default Lab'],
  settings: {
    language: 'ar',
    theme: 'light',
    currency: 'USD',
    appScale: 100,
    defaultCountryCode: '+964',
    isLoggedIn: false,
    rxBackgroundImage: '',
    consentBackgroundImage: '',
    instructionsBackgroundImage: '',
    clinicPhone: '',
    dashboardEnabled: true,
    dashboardPin: '',
    adminPassword: '123456',
    googleDriveLinked: false,
    rxTemplate: {
        rxSymbol: { fontSize: 30, color: '#000000', isBold: true, isItalic: true },
        medications: { fontSize: 14, color: '#000000', isBold: true, isItalic: false },
        topMargin: 100
    },
    consentSettings: { text: '', fontSize: 12, align: 'right', topMargin: 130 },
    instructionSettings: { text: '', fontSize: 12, align: 'right', topMargin: 130 }
  },
  lastUpdated: 0 
};

export const LABELS = {
  en: {
    refreshData: "Refresh Data",
    offline: "Offline",
    gridView: "Grid",
    listView: "List",
    rctLocalSaveWarning: "Saved locally only. Please go to Settings to sync and save changes to the cloud.",
    addTemplate: "Add Template",
    editTemplate: "Edit Template",
    deleteTemplate: "Delete Template",
    applyTemplate: "Apply Template",
    editText: "Edit Text",
    docSettings: "Document Settings",
    headerSpacing: "Header Spacing",
    topMargin: "Top Distance (points)",
    syncLocalFiles: "Sync Local Files",
    unsyncedAlert: "There are local images not saved to cloud yet.",
    goToSettingsToSync: "Go to Settings to sync your files.",
    allSynced: "All files are synchronized.",
    syncingNow: "Syncing files to Drive...",
    shapes: "Shapes",
    rectangle: "Rectangle",
    square: "Square",
    circle: "Circle",
    oval: "Oval",
    diamond: "Diamond",
    arrow: "Arrow",
    curvedArrow: "Curved Arrow",
    rctTool: "Tooth Cross-Section Chart",
    rctToolDesc: "Draw and annotate on the tooth anatomy chart. Changes are saved to patient file.",
    saveToDrive: "Save to Google Drive",
    saveSuccessLocal: "Saved locally to patient file.",
    saveSuccessDrive: "Successfully synced to Google Drive.",
    brush: "Brush",
    size: "Size",
    color: "Color",
    clear: "Clear",
    undo: "Undo",
    eraser: "Eraser",
    featureCloudImages: "Cloud X-ray Storage",
    featureCloudImagesDesc: "Securely sync patient X-rays and photos to the cloud for instant access on all devices.",
    dangerZone: "Danger Zone",
    resetLocalData: "Reset Local Data",
    resetLocalDataDesc: "Deletes all local data on this device. Use this if you encounter sync issues. No cloud data will be deleted.",
    resetConfirmTitle: "Reset Device Cache?",
    resetConfirmMsg: "This will logout and delete local files. Your data remains safe in the cloud and will re-download upon login.",
    deviceNeedsActivation: "Device needs activation",
    deviceActivationDesc: "Please activate this device from the Settings menu to allow uploads.",
    activateDevice: "Activate Device",
    deviceActiveReady: "Device is active and ready",
    syncOnLoad: "Synchronizing cloud data...",
    patientImages: "Patient Images & X-Rays",
    uploadImage: "Upload Image",
    noImages: "No images uploaded yet.",
    googleDriveConnect: "Connect Google Drive",
    googleDriveStatus: "Google Drive Storage",
    linked: "Connected",
    notLinked: "Not Connected",
    confirmDeleteImage: "Are you sure you want to delete this image?",
    errorDrive: "Failed to connect to Google Drive. Please try again.",
    uploadingToDrive: "Uploading to Google Drive...",
    driveNotice: "Images and X-rays are securely saved to your Google Drive account.",
    driveLinkedSuccess: "Google Drive is successfully connected for this clinic on all your devices.",
    linkDriveInSettings: "Please link your Google Drive account from the 'Settings' menu first to enable cloud storage for images.",
    appScale: "Interface Scale",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
    reset: "Reset",
    oldPassword: "Old Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    passwordsMismatch: "Passwords do not match",
    wrongOldPassword: "Old password is incorrect",
    clinicIdentity: "Clinic Identity",
    security: "Security",
    saveChanges: "Save Changes",
    changePassword: "Change Password",
    rxSettings: "Rx Settings",
    rxSymbolStyle: "Rx Symbol Style",
    medsTextStyle: "Medications Text Style",
    generalRxSettings: "General Settings",
    bold: "Bold",
    appTheme: "App Appearance",
    selectTheme: "Select Theme",
    backupOptions: "Backup Options",
    fullBackup: "Full Clinic Data",
    doctorBackup: "Specific Doctor Only",
    restoreOptions: "Restore Options",
    restoreReplace: "Replace (Delete Current)",
    restoreMerge: "Merge (Add New)",
    replaceDesc: "Deletes all current data and replaces it with the backup file.",
    mergeDesc: "Keeps current data and adds patients from the backup file.",
    selectDoctorToBackup: "Select Doctor to Backup",
    searchMedications: "Search medications...",
    manageMedications: "Manage Medications",
    noMedicationsFound: "No medications found",
    deleteMedicationConfirm: "Delete this medication?",
    medicationSaved: "Medication Saved",
    selectProfile: "Select Profile",
    adminAccount: "Main Clinic Admin",
    doctorProfile: "Doctor Profile",
    secretaryProfile: "Secretary",
    manageSecretaries: "Manage Secretaries",
    addSecretary: "Add Secretary",
    editSecretary: "Edit Secretary",
    secretaryName: "Secretary Name",
    maxSecretaries: "Max 4 secretaries allowed",
    enterSecretaryPass: "Enter Secretary Password",
    enterAdminPass: "Enter Main Account Password",
    enterDocPass: "Enter Doctor Password",
    username: "Username",
    password: "Password",
    login: "Login",
    switchProfile: "Switch Profile",
    addProfileFirst: "No doctor profiles found. Please login as Admin to add doctors.",
    manageProfiles: "Manage Profiles",
    profileSettings: "Profile Settings",
    myRxBg: "My Rx Background",
    adminAccessOnly: "Admin Access Only",
    addProfilesHint: "You can add accounts for each doctor or secretary from Settings inside the Main Account.",
    changeAdminPass: "Change Admin Password",
    adminPassword: "Admin Password",
    dashboard: "Statistics", 
    patients: "Patients",
    memos: "Memos",
    calendar: "Calendar",
    finance: "Finance",
    settings: "Settings",
    purchases: "Purchases",
    inventory: "Inventory",
    manageInventory: "Track stock levels and expiry dates",
    addInventoryItem: "Add Item",
    editInventoryItem: "Edit Item",
    currentQty: "Current Qty",
    minQty: "Min Qty",
    expiryDate: "Expiry Date",
    lowStock: "Low Stock",
    expired: "Expired",
    itemColor: "Color",
    clinicName: "Clinic Name",
    doctors: "Doctors",
    addDoctor: "Add Doctor",
    selectDoctor: "Select Doctor",
    searchPatients: "Search patients...",
    active: "Active",
    finished: "Finished",
    pending: "Pending",
    discontinued: "Discontinued",
    newPatient: "New Patient",
    name: "Name",
    phone: "Phone",
    age: "Age",
    gender: "Gender",
    male: "Male",
    female: "Female",
    notes: "Notes",
    medicalHistory: "Medical History",
    save: "Save",
    cancel: "Cancel",
    payments: "Payments",
    appointments: "Appointments",
    totalPaid: "Total Paid",
    totalCost: "Total Cost",
    remaining: "Remaining",
    addPayment: "Add Payment",
    addCharge: "Add Charge",
    printPrescription: "Print Prescription",
    printInvoice: "Print Invoice",
    whatsapp: "WhatsApp",
    call: "Call",
    images: "X-Rays & Images",
    upload: "Upload",
    logout: "Logout",
    welcome: "Welcome to Dentro",
    loginWithGoogle: "Login with Google",
    clinicSetup: "Clinic Setup",
    enterClinicName: "Enter Clinic Name",
    teethChart: "Teeth Chart",
    contactDeveloper: "Developer Contact",
    darkMode: "Dark Mode",
    language: "Language",
    backup: "Download Backup",
    import: "Import Data",
    morning: "AM",
    night: "PM",
    deletePatient: "Delete Patient",
    confirmDelete: "Are you sure you want to delete this patient?",
    address: "Address",
    overview: "Overview",
    files: "Files",
    treatment: "Treatment",
    visitHistory: "Visits",
    financials: "Financials",
    backToPatients: "Back to Patients",
    selectCountry: "Select Country",
    editPatient: "Edit Details",
    registrationDate: "Registered",
    rct: "Root Canal Data",
    sessions: "Treatment Sessions",
    addSession: "Add Session",
    tooth: "Tooth",
    canal: "Canal",
    length: "Length (mm)",
    addRCT: "Add Canal",
    month: "Month",
    week: "Week",
    day: "Day",
    today: "Today",
    newMemo: "New Memo",
    editMemo: "Edit Memo",
    memoTitle: "Title",
    memoContent: "Write your note here...",
    pickColor: "Card Theme",
    category: "Category",
    treatingDoctor: "Treating Doctor",
    setupStep1: "Welcome! Let's set up your clinic.",
    setupStep2: "Now, add the doctors who work here.",
    startApp: "Start Application",
    manageDoctors: "Manage Doctors",
    editClinicName: "Edit Clinic Name",
    treatmentType: "Treatment Type",
    sessionNumber: "Session No.",
    duration: "Duration",
    min: "min",
    session: "Session",
    prescriptions: "Prescriptions",
    newPrescription: "New Prescription",
    drugName: "Drug Name",
    dose: "Dose",
    frequency: "Frequency",
    form: "Form",
    medNotes: "Notes (Optional)",
    addMedication: "Add Medication",
    addMasterDrug: "Manage Medications",
    rxList: "Prescription List",
    print: "Print",
    itemName: "Item Name",
    quantity: "Quantity",
    addItem: "Add Item",
    editItem: "Edit Item",
    installApp: "Install App",
    installDesc: "Install on your device",
    syncing: "Syncing...",
    synced: "Data Synced",
    syncError: "Sync Error",
    landingTitle: "Dentro",
    landingSubtitle: "The complete solution for modern dental clinics.",
    requestTrial: "Request Trial / Subscription",
    pricing: "Pricing Plans",
    filter: "Filter",
    ageGroup: "Age Group",
    under18: "Under 18",
    from18to35: "18 - 35",
    over35: "Over 35",
    applyFilters: "Apply Filters",
    clearFilters: "Clear",
    status: "Status",
    completed: "Completed",
    noShow: "No Show",
    none: "None",
    existingPatient: "Existing Patient",
    quickNewPatient: "Guest Appointment",
    addAppointment: "Add Appointment",
    description: "Description",
    addToPatients: "Add to Patients",
    convertGuestTitle: "Convert to Patient",
    rxBgUrl: "Rx Background (A5)",
    enterRxUrl: "Enter image URL for A5 print background",
    uploadRxBg: "Upload Background",
    removeBg: "Remove",
    treatmentCost: "Treatment Cost",
    paymentReceived: "Payment Received",
    transactionHistory: "Transaction History",
    receipt: "Receipt",
    printChromeWarning: "Printing must be done via Chrome on a PC for the best results.",
    expenses: "Expenses",
    manageExpenses: "Track clinic daily expenses",
    addExpense: "Add Expense",
    editExpense: "Edit Expense",
    price: "Price",
    total: "Total",
    totalExpenses: "Total Expenses",
    expenseDate: "Expense Date",
    deleteExpense: "Delete Expense",
    deleteExpenseConfirm: "Remove this expense?",
    noExpenses: "No expenses found for this period.",
    manageMemos: "Manage your quick notes and reminders",
    noMemos: "No memos yet. Click add to create one.",
    deleteMemo: "Delete Memo",
    deleteMemoConfirm: "Delete this note?",
    managePurchases: "Track materials and supplies needed for the clinic",
    action: "Action",
    noItems: "No items in the list.",
    deleteItem: "Remove this item?",
    registeredPatients: "registered patients",
    noPatientsFilter: "No patients match your search filters.",
    noPatientsCategory: "No patients found in this category.",
    contactWhatsapp: "Contact on WhatsApp",
    back: "Back",
    patientDetails: "Patient Details",
    noMedicalHistory: "No medical history recorded.",
    addNotesPlaceholder: "Add notes here...",
    copyPhone: "Copy Phone",
    appointmentHistory: "Appointment History",
    noVisits: "No visits recorded.",
    at: "at",
    checkup: "Checkup",
    deleteAppointment: "Delete Appointment",
    deleteAppointmentConfirm: "Delete this appointment?",
    deleteRx: "Delete Prescription",
    deleteRxConfirm: "Delete this record?",
    noRx: "No prescriptions recorded yet.",
    rxPlaceholder: "Items will appear here...",
    noTransactions: "No transactions yet.",
    thankYou: "Thank you",
    dateLabel: "Date:",
    manageCalendar: "Manage appointments and schedules",
    noAppsDay: "No appointments for this day.",
    profile: "Profile",
    markCompleted: "Mark Completed",
    markNoShow: "Mark No Show",
    resetStatus: "Reset Status",
    clinicDetails: "Clinic Details",
    done: "Done",
    preferences: "Preferences",
    bgImageSet: "Background image set. To change, remove current one first.",
    recSize: "Recommended size: A5. Supported formats: JPG, PNG.",
    data: "Data",
    cloudSync: "Cloud Sync",
    fullNamePlaceholder: "Full Name",
    country: "Country",
    cityStreetPlaceholder: "City, Street...",
    code: "Code",
    guestNamePlaceholder: "Guest Name",
    optionalNotesPlaceholder: "Optional notes",
    egConsultation: "e.g. Consultation",
    subscribe: "Subscribe",
    fullAccess: "Full Access",
    support: "24/7 Support",
    copyright: "© 2024 Dentro. All rights reserved.",
    next: "Next",
    noDoctors: "No doctors added yet.",
    drNamePlaceholder: "Dr. Name",
    manageClinicSlogan: "Manage your clinic smarter, faster, and better.",
    editAppointment: "Edit Appointment",
    date: "Date",
    clinicPhone: "Clinic Phone",
    printTicket: "Print Ticket",
    appointmentTicket: "Appointment Ticket",
    arriveEarlyNote: "Please arrive 10 minutes before your appointment.",
    time: "Time",
    scheduled: "Scheduled",
    cancelled: "Cancelled",
    noshow: "No Show",
    all: "All",
    thirtyDays: "30 Days",
    selectGender: "Select Gender",
    selectStatus: "Select Status",
    selectAge: "Select Age Group",
    startDate: "From Date",
    endDate: "To Date",
    textNote: "Text Note",
    todoList: "To-Do List",
    addTodo: "Add Task",
    items: "Items",
    materials: "Materials",
    totalPurchases: "Total Purchases",
    convertToExpense: "Convert to Expense",
    confirmConvert: "Move this item to expenses?",
    dashboardTitle: "Dashboard & Analytics",
    monthlyIncome: "Monthly Income",
    monthlyExpenses: "Monthly Expenses",
    netProfit: "Net Profit",
    newPatientsThisMonth: "New Patients",
    vsLastMonth: "vs last month",
    financialOverview: "Financial Overview",
    appointmentStats: "Appointment Stats",
    genderDistribution: "Patients by Gender",
    recentActivity: "Recent Activity",
    income: "Income",
    profit: "Profit",
    enableStats: "Enable Statistics",
    disableStats: "Disable Statistics",
    statsHidden: "Statistics are currently disabled.",
    documents: "Documents",
    consentForm: "Consent Form",
    patientInstructions: "Instructions",
    paperSizeA4: "Paper Size: A4",
    paperSizeA5: "Paper Size: A5",
    addText: "Add Text",
    writeTextHere: "Write your text here to be printed...",
    documentText: "Document Text",
    uploadBg: "Background",
    printDocument: "Print",
    alignRight: "Right",
    alignCenter: "Center",
    alignLeft: "Left",
    fontSize: "Font Size",
    saveTemplate: "Save as Template",
    loadTemplate: "Load Template",
    templateName: "Template Name",
    selectTemplate: "Select a template...",
    generalChart: "General Chart",
    occlusalSurface: "Occlusal & Surfaces",
    headChart: "Head / Face",
    bodyChart: "Body Chart",
    front: "Front",
    backBody: "Back",
    labOrders: "Lab Orders",
    manageLabOrders: "Manage your dental lab requests",
    newLabOrder: "New Order",
    labName: "Lab Name",
    workType: "Work Type",
    toothCount: "No. of Teeth",
    toothNumbers: "Tooth Numbers",
    shade: "Shade",
    sentDate: "Sent Date",
    inProgress: "In Progress",
    ready: "Ready",
    received: "Received",
    selectLab: "Select Lab",
    addLab: "Add Lab",
    enterLabName: "Enter Lab Name",
    selectPatient: "Select Patient",
    editLabOrder: "Edit Lab Order",
    sortBy: "Sort By",
    sortName: "Name (A-Z)",
    sortNewest: "Newest First",
    sortOldest: "Oldest First",
    protectWithPin: "Protect with PIN",
    managePin: "Manage PIN",
    enterPin: "Enter 6-digit PIN",
    setPin: "Set new PIN",
    changePin: "Change PIN",
    removePin: "Remove Protection",
    oldPin: "Old PIN",
    newPin: "New PIN",
    pinSaved: "PIN Saved",
    pinRemoved: "Protection Removed",
    wrongPin: "Incorrect PIN",
    labOrdersStats: "Lab Orders Overview",
    totalLabOrders: "Active Orders",
    readyLabOrders: "Ready to Receive",
    totalLabCost: "Total Lab Expenses",
    locked: "Locked",
    unlockToView: "Enter PIN to view statistics",
    thisWeek: "This Week",
    last30Days: "Last 30 Days",
    vsYesterday: "vs Yesterday",
    vsLastWeek: "vs Last Week",
    vsPreviousPeriod: "vs Previous Period",
    addMedicalHistory: "Add Medical History",
    viewMedicalHistory: "View Medical History",
    addDentalHistory: "Add Dental History",
    editDentalHistory: "Edit Dental History",
    dentalHistory: "Dental History",
    brushingHabits: "Brushing Habits",
    featuresTitle: "Why Choose DENTRO?",
    featuresSubtitle: "A comprehensive solution for modern dental clinics",
    featurePatientMgmt: "Patient Management",
    featurePatientMgmtDesc: "Complete digital files, medical history, and dental history.",
    featureTeethChart: "Interactive Teeth Chart",
    featureTeethChartDesc: "Advanced chart for deciduous and permanent teeth with surface selection and full treatment planning.",
    featureAppointments: "Smart Appointments",
    featureAppointmentsDesc: "Easy scheduling, quick guest appointments, and status tracking.",
    featureFinancials: "Financial Tracking",
    featureFinancialsDesc: "Track income, expenses, patient debts, and installments with detailed reports.",
    featureLabOrders: "Lab Management",
    featureLabOrdersDesc: "Track lab orders status, costs, and shades to ensure timely delivery.",
    featureDocs: "Professional Documents",
    featureDocsDesc: "Print custom prescriptions, invoices, and consent forms with your clinic branding.",
    featureDashboard: "Analytics Dashboard",
    featureDashboardDesc: "Real-time statistics on revenue, patient growth, and clinic performance.",
    featureCloud: "Cloud Sync",
    featureCloudDesc: "Securely access your clinic data from any device, anywhere, anytime.",
    featureMemos: "Memos & Reminders",
    featureMemosDesc: "Keep track of tasks, personal notes, and to-do lists within the app.",
    featureInventory: "Inventory Management",
    featureInventoryDesc: "Track clinic supplies, material costs, and purchases efficiently.",
    featureUpdates: "Continuous Updates",
    featureUpdatesDesc: "We constantly add new features and improvements based on user feedback.",
    featureMore: "More Features",
    featureMoreDesc: "Many other features that help you organize your clinic.",
    featureMultiDoctor: "Multiple Doctors",
    featureMultiDoctorDesc: "Manage multiple dentists with individual accounts and permissions.",
    featureMultiDevice: "Multi-Device Access",
    featureMultiDeviceDesc: "Access your clinic data from phone, tablet, or computer simultaneously.",
    featureProDesigns: "Professional Designs",
    featureProDesignsDesc: "Customizable and professional designs for prescriptions and reports.",
    featureBackup: "Backup & Restore",
    featureBackupDesc: "Keep a secure backup file of all your clinic data and restore it anytime you need.",
    featureThemes: "Multiple Themes",
    featureThemesDesc: "Change the app interface colors to suit your taste with multiple themes.",
    featureMainAccount: "Main Clinic Account",
    featureMainAccountDesc: "Complete control over clinic information, doctors, and full administrative permissions.",
    featureDoctorProfile: "Separate Doctor Profile",
    featureDoctorProfileDesc: "Individual profiles for each doctor containing only their specific patients, details, and statistics.",
    featureSecretaryAccount: "Secretary Account",
    featureSecretaryAccountDesc: "Dedicated account for reception tasks with restricted access to financial data and admin settings.",
    bestValue: "Best Value",
    toothNote: "Note",
    editToothNote: "Edit Tooth Note",
    writeNoteHere: "Write note here...",
    textColor: "Text Color",
    bgColor: "Background",
    titleFormat: "Title Format",
    textFormat: "Text Format",
    italic: "Italic",
    textDir: "Direction",
  },
  ar: {
    refreshData: "تحديث البيانات",
    offline: "غير متصل",
    gridView: "شبكة",
    listView: "قائمة",
    rctLocalSaveWarning: "تم الحفظ محلياً فقط. يرجى الذهاب للإعدادات لمزامنة وحفظ التعديلات على السحابة.",
    addTemplate: "إضافة قالب",
    editTemplate: "تعديل قالب",
    deleteTemplate: "حذف قالب",
    applyTemplate: "تطبيق القالب",
    editText: "تعديل النص",
    docSettings: "إعدادات المطبوع",
    headerSpacing: "مسافة الترويسة",
    topMargin: "المسافة من الأعلى (نقاط)",
    syncLocalFiles: "مزامنة الملفات المحلية",
    unsyncedAlert: "توجد صور ورسومات لم يتم حفظها سحابياً بعد.",
    goToSettingsToSync: "يرجى الذهاب للإعدادات لمزامنة ملفاتك.",
    allSynced: "جميع الملفات تمت مزامنتها بنجاح.",
    syncingNow: "جاري مزامنة الملفات إلى درايف...",
    shapes: "الأشكال",
    rectangle: "مستطيل",
    square: "مربع",
    circle: "دائرة",
    oval: "شكل بيضوي",
    diamond: "معين",
    arrow: "سهم",
    curvedArrow: "سهم منحني",
    rctTool: "مخطط المقطع العرضي للسن",
    rctToolDesc: "ارسم وأشر على مخطط تشريح المقطع العرضي للسن. يتم حفظ التعديلات في ملف المريض.",
    saveToDrive: "حفظ في جوجل درايف",
    saveSuccessLocal: "تم الحفظ محلياً في ملف المريض.",
    saveSuccessDrive: "تمت المزامنة بنجاح مع جوجل درايف.",
    brush: "فرشاة",
    size: "الحجم",
    color: "اللون",
    clear: "مسح الكل",
    undo: "تراجع",
    eraser: "ممحاة",
    featureCloudImages: "تخزين سحابي للأشعة والصور",
    featureCloudImagesDesc: "حفظ ومزامنة كافة صور وأشعة المرضى بأمان على حسابك في Google Drive لضمان عدم ضياعها.",
    dangerZone: "منطقة الخطر",
    resetLocalData: "إعادة ضبط البيانات المحلية",
    resetLocalDataDesc: "سيؤدي هذا إلى حذف كافة البيانات المحلية والملفات المؤقتة على هذا الجهاز. استخدم هذا الخيار في حال واجهت مشاكل في المزامنة. لن يتم حذف أي بيانات من السحابة.",
    resetConfirmTitle: "إعادة ضبط ذاكرة الجهاز؟",
    resetConfirmMsg: "سيتم تسجيل الخروج وحذف الملفات المحلية. بياناتك آمنة في السحابة وسيتم إعادة تحميلها عند تسجيل الدخول مرة أخرى.",
    deviceNeedsActivation: "الجهاز يحتاج تفعيل الاتصال",
    deviceActivationDesc: "يجب تفعيل الاتصال لهذا الجهاز من قائمة الإعدادات للسماح برفع الملفات.",
    activateDevice: "تفعيل الجهاز الآن",
    deviceActiveReady: "الجهاز مفعل وجاهز للرفع",
    syncOnLoad: "جاري مزامنة البيانات السحابية...",
    patientImages: "صور المرضى والأشعة",
    uploadImage: "رفع صورة",
    noImages: "لم يتم رفع صور بعد.",
    googleDriveConnect: "ربط Google Drive",
    googleDriveStatus: "تخزين Google Drive",
    linked: "متصل",
    notLinked: "غير متصل",
    confirmDeleteImage: "هل أنت متأكد من حذف هذه الصورة؟",
    errorDrive: "حدث خطأ في الاتصال بجوجل درايف. يرجى المحاولة مرة أخرى.",
    uploadingToDrive: "جاري الرفع إلى درايف...",
    driveNotice: "يتم حفظ الصور والأشعة تلقائياً وبأمان داخل حساب Google Drive الخاص بك.",
    driveLinkedSuccess: "تم ربط حساب Google Drive بنجاح لهذه العيادة على جميع أجهزتك.",
    linkDriveInSettings: "يرجى ربط حساب Google Drive من قائمة 'الإعدادات' أولاً لتفعيل التخزين السحابي للصور والأشعة.",
    appScale: "حجم الواجهة",
    zoomIn: "تكبير",
    zoomOut: "تصغير",
    reset: "إعادة ضبط",
    oldPassword: "كلمة المرور القديمة",
    newPassword: "كلمة المرور الجديدة",
    confirmNewPassword: "تأكيد كلمة المرور الجديدة",
    passwordsMismatch: "الكلمات المرور غير متطابقة",
    wrongOldPassword: "كلمة المرور القديمة غير صحيحة",
    clinicIdentity: "هوية العيادة",
    security: "الأمان والحماية",
    saveChanges: "حفظ التغييرات",
    changePassword: "تغيير كلمة المرور",
    rxSettings: "إعادة إعدادات الوصفة",
    rxSymbolStyle: "تنسيق كلمة RX",
    medsTextStyle: "تنسيق كتابة الأدوية",
    generalRxSettings: "إعدادات عامة",
    bold: "غامق",
    appTheme: "مظهر التطبيق",
    selectTheme: "اختر الثيم",
    backupOptions: "خيارات النسخ الاحتياطي",
    fullBackup: "بيانات العيادة بالكامل",
    doctorBackup: "طبيب محدد فقط",
    restoreOptions: "خيارات الاستعادة",
    restoreReplace: "استبدال (حذف الحالي)",
    restoreMerge: "إضافة (دمج)",
    replaceDesc: "يحذف جميع البيانات الحالية ويستبدلها بالبيانات الموجودة في الملف.",
    mergeDesc: "يحافظ على البيانات الحالية ويضيف الأسماء والبيانات من ملف النسخ الاحتياطي.",
    selectDoctorToBackup: "اختر الطبيب لنسخ بياناته",
    searchMedications: "بحث عن دواء...",
    manageMedications: "إدارة الأدوية",
    noMedicationsFound: "لا توجد أدوية",
    deleteMedicationConfirm: "حذف هذا الدواء من القائمة؟",
    medicationSaved: "تم حفظ الدواء",
    selectProfile: "اختر الحساب",
    adminAccount: "الحساب الأساسي (العيادة)",
    doctorProfile: "بروفايل طبيب",
    secretaryProfile: "سكرتير",
    manageSecretaries: "إدارة السكرتارية",
    addSecretary: "إضافة سكرتير",
    editSecretary: "تعديل سكرتير",
    secretaryName: "اسم السكرتير",
    maxSecretaries: "الحد الأقصى 4 سكرتير",
    enterSecretaryPass: "أدخل كلمة مرور السكرتير",
    enterAdminPass: "أدخل كلمة مرور الحساب الأساسي",
    enterDocPass: "أدخل كلمة مرور الطبيب",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    login: "تسجيل الدخول",
    switchProfile: "تبديل الحساب",
    addProfileFirst: "لا يوجد أطباء مسجلين. يرجى الدخول للحساب الأساسي لإضافة أطباء.",
    manageProfiles: "إدارة الحسابات",
    profileSettings: "إعدادات البروفايل",
    myRxBg: "خلفية الوصفة الخاصة بي",
    adminAccessOnly: "صلاحيات الأدمن فقط",
    addProfilesHint: "يمكنك إضافة حسابات لكل طبيب أو للسكرتير من داخل الإعدادات في الحساب الأساسي.",
    changeAdminPass: "تغيير كلمة مرور المسؤول",
    adminPassword: "Admin Password",
    dashboard: "الإحصائيات",
    patients: "المرضى",
    memos: "المذكرات",
    calendar: "التقويم",
    finance: "المالية",
    settings: "الإعدادات",
    purchases: "المشتريات",
    inventory: "المخزن",
    manageInventory: "تتبع المواد ومستويات المخزون",
    addInventoryItem: "إضافة مادة",
    editInventoryItem: "تعديل المادة",
    currentQty: "الكمية الحالية",
    minQty: "أقل كمية",
    expiryDate: "تاريخ الانتهاء",
    lowStock: "مخزون منخفض",
    expired: "منتهي الصلاحية",
    itemColor: "لون العنصر",
    clinicName: "اسم العيادة",
    doctors: "الأطباء",
    addDoctor: "إضافة طبيب",
    selectDoctor: "اختر الطبيب",
    searchPatients: "بحث عن مريض...",
    active: "مستمر بالعلاج",
    finished: "منتهي",
    pending: "لم يبدأ",
    discontinued: "لم يستمر",
    newPatient: "مريض جديد",
    name: "الاسم الكامل",
    phone: "رقم الهاتف",
    age: "العمر",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    notes: "الملاحظات",
    medicalHistory: "التاريخ الطبي",
    save: "حفظ",
    cancel: "إلغاء",
    payments: "الدفعات",
    appointments: "المواعيد",
    totalPaid: "الواصل",
    totalCost: "الكلي",
    remaining: "المتبقي",
    addPayment: "إضافة دفعة",
    addCharge: "إضافة تكلفة علاج",
    printPrescription: "طباعة وصفة",
    printInvoice: "طباعة وصل",
    whatsapp: "واتساب",
    call: "اتصال",
    images: "الأشعة والصور",
    upload: "رفع صورة",
    logout: "تسجيل خروج",
    welcome: "مرحباً بك في Dentro",
    loginWithGoogle: "تسجيل الدخول عبر Google",
    clinicSetup: "إعداد العيادة",
    enterClinicName: "أدخل اسم العيادة",
    teethChart: "مخطط الأسنان",
    contactDeveloper: "تواصل مع المطور",
    darkMode: "الوضع الليلي",
    language: "الغة",
    backup: "نسخ احتياطي",
    import: "استيراد بيانات",
    morning: "صباحاً",
    night: "مساءً",
    deletePatient: "حذف المريض",
    confirmDelete: "هل أنت متأكد من حذف هذا المريض وكل بياناته؟",
    address: "العنوان",
    overview: "نظرة عامة",
    files: "الملفات",
    treatment: "العلاج",
    visitHistory: "الزيارات",
    financials: "المالية",
    backToPatients: "العودة للقائمة",
    selectCountry: "اختر الدولة",
    editPatient: "تعديل المعلومات",
    registrationDate: "تاريخ التسجيل",
    rct: "قياسات القنوات (RCT)",
    sessions: "جلسات العلاج",
    addSession: "إضافة جلسة",
    tooth: "السن",
    canal: "القناة",
    length: "الطول (ملم)",
    addRCT: "إضافة قناة",
    month: "شهر",
    week: "أسبوع",
    day: "يوم",
    today: "اليوم",
    newMemo: "مذكرة جديدة",
    editMemo: "تعديل المذكرة",
    memoTitle: "العنوان",
    memoContent: "اكتب ملاحظتك هنا...",
    pickColor: "خلفية البطاقة",
    category: "التصنيف",
    treatingDoctor: "الطبيب المعالج",
    setupStep1: "مرحباً! لنقم بإعداد عيادتك.",
    setupStep2: "الآن، أضف أسماء الأطباء العاملين.",
    startApp: "بدء التطبيق",
    manageDoctors: "إدارة الأطباء",
    editClinicName: "تعديل اسم العيادة",
    treatmentType: "نوع العلاج",
    sessionNumber: "رقم الجلسة",
    duration: "مدة الجلسة",
    min: "دقيقة",
    session: "جلسة",
    prescriptions: "الوصفات",
    newPrescription: "وصفة جديدة",
    drugName: "اسم العلاج",
    dose: "الجرعة",
    frequency: "التكرار",
    form: "الشكل",
    medNotes: "ملاحظات (اختياري)",
    addMedication: "إضافة دواء للوصفة",
    addMasterDrug: "إدارة الأدوية",
    rxList: "قائمة الوصفات",
    print: "طباعة",
    itemName: "اسم المادة",
    quantity: "العدد",
    addItem: "إضافة مادة",
    editItem: "تعديل مادة",
    installApp: "تثبيت التطبيق",
    installDesc: "تثبيت على جهازك",
    syncing: "جاري المزامنة...",
    synced: "تمت المزامنة",
    syncError: "خطأ في المزامنة",
    landingTitle: "Dentro",
    landingSubtitle: "الحل المتكامل لإدارة العيادات الحديثة",
    requestTrial: "طلب نسخة تجريبية / اشتراك",
    pricing: "باقات الاشتراك",
    filter: "فلترة",
    ageGroup: "الفئة العمرية",
    under18: "أقل من 18",
    from18to35: "18 - 35",
    over35: "أكبر من 35",
    applyFilters: "تطبيق الفلتر",
    clearFilters: "مسح",
    status: "الحالة",
    completed: "تم",
    noShow: "لم يأتي",
    none: "بلا",
    existingPatient: "مريض حالي",
    quickNewPatient: "موعد جديد",
    addAppointment: "إضافة موعد",
    description: "الوصف (اختياري)",
    addToPatients: "إضافة للمرضى",
    convertGuestTitle: "تحويل إلى مريض",
    rxBgUrl: "خلفية الوصفة (A5)",
    enterRxUrl: "أدخل رابط الصورة للخلفية",
    uploadRxBg: "رفع صورة خلفية",
    removeBg: "إزالة",
    treatmentCost: "تكلفة العلاج",
    paymentReceived: "دفعة واصلة",
    transactionHistory: "سجل الدفعات",
    receipt: "وصل قبض",
    printChromeWarning: "يجب ان تكون عملية الطباعة من خلال متصفح Chrome على الكمبيوتر لتتم عملية الطباعة بصورة صحيحة.",
    expenses: "الصرفيات",
    manageExpenses: "تتبع نفقات العيادة اليومية",
    addExpense: "إضافة صرفيات",
    editExpense: "تعديل السجل",
    price: "السعر",
    total: "الإجمالي",
    totalExpenses: "مجموع الصرفيات",
    expenseDate: "تاريخ الصرف",
    deleteExpense: "حذف الصرفيات",
    deleteExpenseConfirm: "هل تريد حذف هذا السجل؟",
    noExpenses: "لا توجد صرفيات لهذه الفترة.",
    manageMemos: "أدر ملاحظاتك السريعة والتذكيرات",
    noMemos: "لا توجد مذكرات. اضغط إضافة لإنشاء واحدة.",
    deleteMemo: "حذف المذكرة",
    deleteMemoConfirm: "هل تريد حذف هذه الملاحظة؟",
    managePurchases: "تتبع المواد والمستلزمات المطلوبة للعيادة",
    action: "إجراء",
    noItems: "لا توجد عناصر في القائمة.",
    deleteItem: "إزالة هذا العنصر؟",
    registeredPatients: "مرضى مسجلين",
    noPatientsFilter: "لا يوجد مرضى يطابقون البحث.",
    noPatientsCategory: "لا يوجد مرضى في هذا التصنيف.",
    contactWhatsapp: "تواصل عبر واتساب",
    back: "رجوع",
    patientDetails: "تفاصيل المريض",
    noMedicalHistory: "لم يسجل أي تاريخ طبي.",
    addNotesPlaceholder: "أضف ملاحظات هنا...",
    copyPhone: "نسخ الهاتف",
    appointmentHistory: "سجل المواعيد",
    noVisits: "لا توجد زيارات مسجلة.",
    at: "at",
    checkup: "فحص",
    deleteAppointment: "حذف الموعد",
    deleteAppointmentConfirm: "حذف هذا الموعد؟",
    deleteRx: "تعديل الوصفة",
    deleteRxConfirm: "هل تريد حذف هذا السجل؟",
    noRx: "No prescriptions recorded yet.",
    rxPlaceholder: "ستظهر العناصر هنا...",
    noTransactions: "لا توجد معاملات بعد.",
    thankYou: "شكراً لك",
    dateLabel: "التاريخ:",
    manageCalendar: "إدارة المواعيد والجداول",
    noAppsDay: "لا توجد مواعيد لهذا اليوم.",
    profile: "الملف الشخصي",
    markCompleted: "تحديد كمكتمل",
    markNoShow: "تحديد كعدم حضور",
    resetStatus: "إعادة تعيين الحالة",
    clinicDetails: "تفاصيل العيادة",
    done: "تم",
    preferences: "التفضيلات",
    bgImageSet: "تم تعيين الخلفية.",
    recSize: "الحجم الموصى به: A5. الصيغة المدعومة: JPG, PNG.",
    data: "البيانات",
    cloudSync: "المزامنة السحابية",
    fullNamePlaceholder: "الاسم الكامل",
    country: "الدولة",
    cityStreetPlaceholder: "المدينة، الشارع...",
    code: "الرمز",
    guestNamePlaceholder: "اسم الزائر",
    optionalNotesPlaceholder: "ملاحظات اختيارية",
    egConsultation: "مثلاً: استشارة",
    subscribe: "اشترك",
    fullAccess: "وصول كامل",
    support: "دعم فني 24/7",
    copyright: "© 2024 Dentro. جميع الحقوق محفوظة.",
    next: "التالي",
    noDoctors: "لم يتم إضافة أطباء بعد.",
    drNamePlaceholder: "اسم الطبيب",
    manageClinicSlogan: "إدارة عيادتك بذكاء وسرعة وكفاءة.",
    editAppointment: "تعديل الموعد",
    date: "التاريخ",
    clinicPhone: "هاتف العيادة",
    printTicket: "طباعة تذكرة",
    appointmentTicket: "تذكرة موعد",
    arriveEarlyNote: "يرجى الحضور قبل الموعد بـ 10 دقائق.",
    time: "الوقت",
    scheduled: "مجدول",
    cancelled: "ملغي",
    noshow: "لم يحضر",
    all: "الكل",
    thirtyDays: "30 يوم",
    selectGender: "اختر الجنس",
    selectStatus: "اختر الحالة",
    selectAge: "اختر الفئة العمرية",
    startDate: "من تاريخ",
    endDate: "إلى تاريخ",
    textNote: "ملاحظة نصية",
    todoList: "قائمة مهام",
    addTodo: "إضافة مهمة",
    items: "المهام",
    materials: "Materials",
    totalPurchases: "مجموع المشتريات",
    convertToExpense: "تحويل إلى صرفيات",
    confirmConvert: "تحويل هذا العنصر إلى الصرفيات؟",
    dashboardTitle: "الإحصائيات والأرقام",
    monthlyIncome: "الدخل الشهري",
    monthlyExpenses: "المصاريف الشهرية",
    netProfit: "الأرباح",
    newPatientsThisMonth: "مرضى جدد",
    vsLastMonth: "مقارنة بالشهر السابق",
    financialOverview: "الملخص المالي",
    appointmentStats: "إحصائيات المواعيد",
    genderDistribution: "توزيع المرضى حسب الجنس",
    recentActivity: "آخر العمليات",
    income: "الدخل",
    profit: "الأرباح",
    enableStats: "تفعيل الإحصائيات",
    disableStats: "إخفاء الإحصائيات",
    statsHidden: "تم إخفاء الإحصائيات حالياً.",
    documents: "المطبوعات",
    consentForm: "ورقة موافقة عمل",
    patientInstructions: "تعليمات للمريض",
    paperSizeA4: "حجم الورقة: A4",
    paperSizeA5: "حجم الورقة: A5",
    addText: "إضافة نص",
    writeTextHere: "اكتب النص المراد طباعته هنا...",
    documentText: "نص الوثيقة",
    uploadBg: "الخلفية",
    printDocument: "طباعة",
    alignRight: "يمين",
    alignCenter: "وسط",
    alignLeft: "يسار",
    fontSize: "خط",
    saveTemplate: "حفظ كقالب",
    loadTemplate: "تحميل قالب",
    templateName: "اسم القالب",
    selectTemplate: "اختر قالباً...",
    generalChart: "مخطط عام",
    occlusalSurface: "الأسطح (Occlusal)",
    headChart: "مخطط الرأس والوجه",
    bodyChart: "مخطط الجسم",
    front: "أمام",
    backBody: "خلف",
    labOrders: "طلبات المختبر",
    manageLabOrders: "إدارة طلبات مختبر الأسنان",
    newLabOrder: "طلب جديد",
    labName: "اسم المختبر",
    workType: "نوع العمل",
    toothCount: "عدد الأسنان",
    toothNumbers: "أرقام الأسنان",
    shade: "اللون (Shade)",
    sentDate: "تاريخ الإرسال",
    inProgress: "قيد التنفيذ",
    ready: "جاهز للاستلام",
    received: "تم الاستلام",
    selectLab: "اختر المختبر",
    addLab: "إضافة مختبر",
    enterLabName: "أدخل اسم المختبر",
    selectPatient: "اختر المريض",
    editLabOrder: "تعديل الطلب",
    sortBy: "ترتيب حسب",
    sortName: "الاسم (أ-ي)",
    sortNewest: "الأحدث أولاً",
    sortOldest: "الأقدم أولاً",
    protectWithPin: "حماية برمز PIN",
    managePin: "إدارة الرمز",
    enterPin: "أدخل الرمز (6 أرقام)",
    setPin: "تغيير رمز جديد",
    changePin: "تغيير الرمز",
    removePin: "إزالة الحماية",
    oldPin: "الرمز القديم",
    newPin: "الرمز الجديد",
    pinSaved: "تم حفظ الرمز",
    pinRemoved: "تمت إزالة الحماية",
    wrongPin: "الرمز خاطئ",
    labOrdersStats: "ملخص طلبات المختبر",
    totalLabOrders: "طلبات فعالة",
    readyLabOrders: "جاهز للاستلام",
    totalLabCost: "تكاليف المختبر",
    locked: "Locked",
    unlockToView: "أدخل الرمز لعرض الإحصائيات",
    thisWeek: "هذا الأسبوع",
    last30Days: "آخر 30 يوم",
    vsYesterday: "مقارنة بالأمس",
    vsLastWeek: "مقارنة بالأسبوع الماضي",
    vsPreviousPeriod: "مقارنة بالفترة السابقة",
    addMedicalHistory: "إضافة تاريخ طبي",
    viewMedicalHistory: "عرض التاريخ الطبي",
    addDentalHistory: "إضافة تاريخ سني",
    editDentalHistory: "تعديل التاريخ السني",
    dentalHistory: "التاريخ السني",
    brushingHabits: "عادات تنظيف الأسنان",
    featuresTitle: "لماذا تختار DENTRO؟",
    featuresSubtitle: "الحل المتكامل والأمثل لعيادات الأسنان الحديثة",
    featurePatientMgmt: "إدارة المرضى",
    featurePatientMgmtDesc: "ملفات إلكترونية كاملة، تاريخ مرضي، وتاريخ سني.",
    featureTeethChart: "مخطط الأسنان التفاعلي",
    featureTeethChartDesc: "مخطط متطور للأسنان اللبنية والدائمية مع تحديد الأسطح وخطط العلاج.",
    featureAppointments: "المواعيد الذكية",
    featureAppointmentsDesc: "جدولة سهلة، مواعيد سريعة للزوار وتتبع الحالات.",
    featureFinancials: "الإدارة المالية",
    featureFinancialsDesc: "تتبع الدخل، المصاريف، ديون المرضى، والأقساط مع تقارير دقيقة.",
    featureLabOrders: "متابعة المختبر",
    featureLabOrdersDesc: "تتبع حالات طلبات المختبر، التكاليف، والألوان لضمان التسليم.",
    featureDocs: "المطبوعات والوثائق",
    featureDocsDesc: "طباعة الوصفات الطبية، الوصولات، ونماذج الموافقة بتصاميم عيادتك.",
    featureDashboard: "لوحة التحكم والإحصائيات",
    featureDashboardDesc: "إحصائيات فورية عن الأرباح، نمو المرضى، وأداء العيادة.",
    featureCloud: "المزامنة السحابية",
    featureCloudDesc: "وصول آمن لبيانات عيادتك من أي جهاز وفي أي وقت.",
    featureMemos: "المذكرات والملاحظات",
    featureMemosDesc: "تتبع المهام، الملاحظات الشخصية، وقوائم العمل داخل التطبيق.",
    featureInventory: "إدارة المخزون",
    featureInventoryDesc: "تتبع مستلزمات العيادة، تكاليف المواد، والمشتريات بكفاءة.",
    featureUpdates: "تحديثات مستمرة",
    featureUpdatesDesc: "نضيف ميزاتٍ جديدة ونحسن النظام باستمرار بناءً على مقترحاتكم.",
    featureMore: "ميزات أخرى",
    featureMoreDesc: "الكثير من الميزات الأخرى التي تساعدك في تنظيم عيادتك.",
    featureMultiDoctor: "أطباء متعددين",
    featureMultiDoctorDesc: "إدارة عدة أطباء بحسابات وصلاحيات فردية.",
    featureMultiDevice: "أجهزة متعددة",
    featureMultiDeviceDesc: "وصول لبيانات العيادة من الهاتف، التابلت، أو الكمبيوتر في آن واحد.",
    featureProDesigns: "تصاميم احترافية",
    featureProDesignsDesc: "تصاميم قابلة للتخصص واحترافية للوصفات الطبية والتقارير.",
    featureBackup: "نسخ احتياطي واستعادة",
    featureBackupDesc: "احتفظ بملف نسخة احتياطية آمنة لكل بيانات عيادتك واستعدها في أي وقت تحتاجه.",
    featureThemes: "ثيمات متنوعة",
    featureThemesDesc: "تغيير ألوان واجهة التطبيق لتناسب ذوقك مع ثيمات متنوعة.",
    featureMainAccount: "حساب العيادة الأساسي",
    featureMainAccountDesc: "تحكم كامل في معلومات العيادة، الأطباء، وصلاحيات إدارية شاملة.",
    featureDoctorProfile: "بروفايل طبيب منفصل",
    featureDoctorProfileDesc: "ملفات فردية لكل طبيب تحتوي فقط على مرضاه الخاصين وتفاصيله وإحصائياته.",
    featureSecretaryAccount: "حساب السكرتير",
    featureSecretaryAccountDesc: "حساب مخصص لمهام الاستقبال مع وصول محدود للبيانات المالية وإعدادات المشرف.",
    bestValue: "أفضل قيمة",
    toothNote: "ملاحظة",
    editToothNote: "تعديل ملاحظة السن",
    writeNoteHere: "اكتب الملاحظة هنا...",
    textColor: "لون النص",
    bgColor: "خلفية",
    titleFormat: "تنسيق العنوان",
    textFormat: "تنسيق النص",
    italic: "مائل",
    textDir: "اتجاة النص",
  },
  ku: {
    refreshData: "نوێکردنەوەی داتا",
    offline: "هێڵ نییە",
    gridView: "تۆڕ",
    listView: "لیست",
    rctLocalSaveWarning: "بە شێوەیەکی ناوخۆیی پاشەکەوت کرا. تکایە بڕۆ بۆ ڕێکخستنەکان بۆ هاوکاتکردن و پاشەکەوتکردنی گۆڕانکارییەکان لەسەر هەور.",
    addTemplate: "قاڵب زیادبکە",
    editTemplate: "قاڵب دەستکاری بکە",
    deleteTemplate: "قاڵب بسڕەوە",
    applyTemplate: "جێبەجێکردنی قاڵب",
    editText: "دەستکاری دەق",
    docSettings: "ڕێکخستنی چاپکراو",
    headerSpacing: "بۆشایی سەرەوە",
    topMargin: "بۆشایی لە سەرەوە (خاڵ)",
    syncLocalFiles: "هاوکاتکردنی فایلە ناوخۆییەکان",
    unsyncedAlert: "هەندێک وێنە و هێڵکاری هەن کە هێشتا لەسەر هەور پاشەکەوت nەکراون.",
    goToSettingsToSync: "تکایە بڕۆ بۆ ڕێکخستنەکان بۆ هاوکاتکردنی فایلەکانت.",
    allSynced: "هەموو فایلەکان بە سەرکەوتوویی هاوکات کراون.",
    syncingNow: "فایلەکان بۆ درایڤ هاوکات دەکرێن...",
    shapes: "الأشكال",
    rectangle: "مستطيل",
    square: "مربع",
    circle: "دائرة",
    oval: "شكل بيضوي",
    diamond: "معين",
    arrow: "سهم",
    curvedArrow: "سهم منحني",
    rctTool: "مخطط المقطع العرضي للسن",
    rctToolDesc: "نەخشەی بڕگەی تەنیشتی ددان. گۆڕانکارییەکان لە فایلی نەخۆشەکە پاشەکەوت دەبن.",
    saveToDrive: "...پاشەکەوتکردن لە Google Drive",
    saveSuccessLocal: "بە سەرکەوتوویی لە فایلی نەخۆشەکە پاشەکەوت کرا.",
    saveSuccessDrive: "بە سەرکەوتوویی لەگەڵ Google Drive هاوکات کرا.",
    brush: "فڵچە",
    size: "خاڵ",
    color: "ڕەنگ",
    clear: "سڕینەوەی هەموو",
    undo: "گەڕانەوە",
    eraser: "سڕەرەوە",
    featureCloudImages: "کۆگای تیشک و وێنەکان",
    featureCloudImagesDesc: "هەموو وێنە و تیشکەکانی نەخۆش بە سەلامەتی لە هەژماری Google Drive پاشەکەوت دەکرێن.",
    dangerZone: "ناوچەی مەترسی",
    resetLocalData: "سڕینەوەی داتا ناوخۆییەکان",
    resetLocalDataDesc: "ئەمە دەبێتە هۆی سڕینەوەی هەموو داتا و فایلە کاتییەکان لەسەر ئەم ئامێرە. ئەمە بەکاربێنە ئەگەر کێشەی هاوکاتکردنت هەبوو. هیچ داتایەک لە سحابة ناسڕێتەوە.",
    resetConfirmTitle: "داتاکانی ئەم ئامێرە دەسڕیتەوە؟",
    resetConfirmMsg: "لە هەژمارەکەت دەچیتە دەرەوە و فایلە ناوخۆییەکان دەسڕدرێنەوە. داتاکانت پارێزراون و دووبارە دادەگیرێنەوە کاتێک دەچیتەوە ژوورەوە.",
    deviceNeedsActivation: " ئامێرەکە پێویستی بە چالاککردن هەیە",
    deviceActivationDesc: "تکایە ئەم ئامێرە لە بەشی ڕێکخستنەکان چالاک بکە بۆ ئەوەی ڕێگەت پێبدرێت فایلەکان بەرز بکەیتەوە.",
    activateDevice: "چالاککردنی ئامێر",
    deviceActiveReady: "ئامێرەکە چالاکە و ئامادەیە",
    syncOnLoad: "هاوکاتکردنی داتای هەوری...",
    patientImages: "وێنەی نەخۆشەکان و تیشک",
    uploadImage: "بەرزکردنەوەی وێنە",
    noImages: "هیچ وێنەیەک بەرزنەکراوەتەوە.",
    googleDriveConnect: "بەستنەوە بە Google Drive",
    googleDriveStatus: "کۆگای Google Drive",
    linked: "بەستراوەتەوە",
    notLinked: "نەبەستراوەتەوە",
    confirmDeleteImage: "دڵنیای لە سڕینەوەی ئەم وێنەیە؟",
    errorDrive: "کێشەیەک لە پەیوەندی بە گووگڵ درایڤ دروست بوو.",
    uploadingToDrive: "وێنەکە بۆ درایڤ بەرز دەکرێتەوە...",
    driveNotice: "وێنە و تیشکەکان بە شێوەیەکی پارێزراو لە ناو هەژماری Google Drive ي خۆتدا پاشەکەوت دەکرێن.",
    driveLinkedSuccess: "هەژماری Google Drive بە سەرکەوتوویی بۆ ئەم کلینیکە لەسەر هەموو ئامێرەکانت بەستراوەتەوە.",
    linkDriveInSettings: "تکایە سەرەتا هەژماری Google Drive لە بەشی 'ڕێکخستنەکان' ببەستەرەوە بۆ ئەوەی وێنە و تیشکەکان پاشەکەوت بکرێن.",
    appScale: "قەبارەی ڕووکار",
    zoomIn: "گەورەکردن",
    zoomOut: "بچووكکردنەوە",
    reset: "ڕێکخستنەوە",
    oldPassword: "وشەی تێپەڕی کۆن",
    newPassword: "وشەی تێپەڕی نوێ",
    confirmNewPassword: "دووپاتکردنەوەی وشەی تێپەڕ",
    passwordsMismatch: "وشەکان وەک یەک نین",
    wrongOldPassword: "وشەی کۆن هەڵەیە",
    clinicIdentity: "ناسنامەی کلینیک",
    security: "پاراستن و ئاسایش",
    saveChanges: "پاراستنی گۆڕانکارییەکان",
    changePassword: "گەڕینی وشەی تێپەڕ",
    rxSettings: "ڕێکخستنی ڕەچەتە",
    rxSymbolStyle: "شێوازي پیتی RX",
    medsTextStyle: "شێوازی نووسینی دەرمان",
    generalRxSettings: "ڕێکخستنی گشتی",
    bold: "تۆخ",
    appTheme: "ڕووکاری بەرنامە",
    selectTheme: "دیاریکردنی ڕووکار",
    backupOptions: "هەڵبژاردەکانی هەڵگرتن",
    fullBackup: "تەواوی داتای کلینیک",
    doctorBackup: "تەنها پزیشکێکی دیاریکراو",
    restoreOptions: "هەڵبژاردەکانی گەڕاندنەوە",
    restoreReplace: "سڕینەوەی ئێستا",
    restoreMerge: "زیادکردن",
    replaceDesc: "تەواوی داتاکانی ئێستا دەسڕێتەوە و داتای ناو فایلەکە دادەنێت.",
    mergeDesc: "داتاکانی ئێستا دەپارێزێت و ناوی نەخۆشەکان لە فایلەکەوە زیاد دەکات.",
    selectDoctorToBackup: "پزیشک دیاریبکە بۆ هەڵگرتنی داتاکانی",
    searchMedications: "گەڕان بۆ دەرمان...",
    manageMedications: "بەڕێوەبردنی دەرمانەکان",
    noMedicationsFound: "هیچ دەرمانێک نەدۆزرایەوە",
    deleteMedicationConfirm: "دەتەوێت ئەم دەرمانە بسڕیتەوە؟",
    medicationSaved: "دەرمانەکە هەڵگیرا",
    selectProfile: "هەژمار دیاریبکە",
    adminAccount: "هەژماری سەرەکی (کلینیک)",
    doctorProfile: "پرۆفایلی پزیشک",
    secretaryProfile: "سکرتێر",
    manageSecretaries: "بەڕێوەبردنی سکرتێر",
    addSecretary: "زیادکردنی سکرتێر",
    editSecretary: "دەستکاری سکرتێر",
    secretaryName: "ناوی سکرتێر",
    maxSecretary: "تەنها ٤ سکرتێر ڕێگەپێدراوە",
    enterSecretaryPass: "وشەی تێپەڕی سکرتێر بنووسە",
    enterAdminPass: "وشەی تێپەڕی هەژماری سەرەکی بنووسە",
    enterDocPass: "وشەی تێپەڕی پزیشک بنووسە",
    username: "ناوی بەکارهێنەر",
    password: "وشەی تێپەڕ",
    login: "چوونەژوورەوە",
    switchProfile: "گەڕانی هەژمار",
    addProfileFirst: "هیچ پزیشکێک نییە. تکایە سەرەتا بە هەژماری سەرەکی بچۆ ژوورەوە بۆ زیادکردنی پزیشک.",
    manageProfiles: "بەڕێوەبردنی پرۆفایلەکان",
    profileSettings: "رێکخستنی پرۆفایل",
    myRxBg: "وێنەی باکگراوند ڕەچەتەکەم",
    adminAccessOnly: "تەنها بۆ ئەدمین",
    addProfilesHint: "دەتوانیت هەژماری پزیشک یان سکرتێر زیاد بکەیت لە ڕێکخستنەکانی هەژماری سەرەکی.",
    changeAdminPass: "گەڕینی وشەی تێپەڕی ئەدمین",
    adminPassword: "وشەی تێپەڕی ئەدمین",
    dashboard: "ئامارەکان",
    patients: "نەخۆشەکان",
    memos: "تێبینیەکان",
    calendar: "رۆژمێر",
    finance: "دارایی",
    settings: "ڕێکخستنەکان",
    purchases: "کڕینەکان",
    inventory: "کۆگا",
    manageInventory: "تتبع المواد ومستويات المخزون",
    addInventoryItem: "زیادکردنی ماددە",
    editInventoryItem: "دەستکاری ماددە",
    currentQty: "بڕی ئێستا",
    minQty: "کەمترین بڕ",
    expiryDate: "بەرواری بەسەرچوون",
    lowStock: "کەمبوونەوەی کۆگا",
    expired: "بەسەرچوو",
    itemColor: "ڕەنگی ماددە",
    clinicName: "ناوی کلینیک",
    doctors: "پزیشکەکان",
    addDoctor: "زیادکردنی پزیشک",
    selectDoctor: "پزیشک دیاریبکە",
    searchPatients: "گەڕان بۆ نەخۆش...",
    active: "بەردەوام",
    finished: "تەواوبوو",
    pending: "دەستی پێنەکردووە",
    discontinued: "بەردەوام نەبوو",
    newPatient: "نەخۆشی نوێ",
    name: "ناوی تەواو",
    phone: "ژمارەی مۆبایل",
    age: "تەمەن",
    gender: "ڕەگەز",
    male: "نێر",
    female: "مێ",
    notes: "تێبینی",
    medicalHistory: "مێژووی پزیشکی",
    save: "خەزنکردن",
    cancel: "هەڵوەشاندنەوە",
    payments: "پارەدانەکان",
    appointments: "کاتەکان",
    totalPaid: "دراوە",
    totalCost: "کۆی گشتی",
    remaining: "ماوە",
    addPayment: "زیادکردنی پارە",
    addCharge: "زیادکردنی تێچوو",
    printPrescription: "چاپکردنی ڕەچەتە",
    printInvoice: "چاپکردنی پسوڵە",
    whatsapp: "واتسئەپ",
    call: "پەیوەندی",
    images: "وێنە و تیشک",
    upload: "بەرزکردنەوە",
    logout: "دەرچوون",
    welcome: "بەخێربێن بۆ Dentro",
    loginWithGoogle: "چوونەژوورەوە بە گۆگڵ",
    clinicSetup: "رێکخستنی کلینیک",
    enterClinicName: "ناوی کلینیک بنووسە",
    teethChart: "هێڵکاری ددان",
    contactDeveloper: "پەیوەندی بە گەشەپێدەر",
    darkMode: "دۆخی تاریک",
    language: "زمان",
    backup: "هەڵگرتنی داتا",
    import: "هێنانى داتا",
    morning: "بەیانی",
    night: "ئێوارە",
    deletePatient: "سڕینەوەی نەخۆش",
    confirmDelete: "دڵنیای لە سڕینەوەی ئەم نەخۆشە؟",
    address: "ناونیشان",
    overview: "پوختە",
    files: "فایلەکان",
    treatment: "چارەسەر",
    visitHistory: "سەردانەکان",
    financials: "دارایی",
    backToPatients: "گەڕانەوە بۆ لیست",
    selectCountry: "وڵات دیاریبکە",
    editPatient: "دەستکاری زانیاری",
    registrationDate: "بەرواری تۆمار",
    rct: "پێوانی کەناڵەکان",
    sessions: "دانیشتنەکانی چارەسەر",
    addSession: "زیادکردنی دانیشتن",
    tooth: "ددان",
    canal: "کەناڵ",
    length: "درێژی (ملم)",
    addRCT: "زیادکردنی کەناڵ",
    month: "مانگ",
    week: "هەفتە",
    day: "رۆژ",
    today: "ئەمڕۆ",
    newMemo: "تێبینی نوێ",
    editMemo: "دەستکاری تێبینی",
    memoTitle: "ناونیشان",
    memoContent: "تێبینی بنووسە...",
    pickColor: "ڕەنگی کارت",
    category: "جۆر",
    treatingDoctor: "پزیشکی چارەسەرکار",
    setupStep1: "بەخێربێن! با کلینیکەکەت ڕێکبخەین.",
    setupStep2: "ئێستا، ناوی پزیشکەکان زیاد بکە.",
    startApp: "دەستپێکردن",
    manageDoctors: "بەڕێوەبردنی پزیشکەکان",
    editClinicName: "دەستکاری ناوی کلینیک",
    treatmentType: "جۆری چارەسەر",
    sessionNumber: "ژمارەی دانیشتن",
    duration: "ماوە",
    min: "خوولەک",
    session: "دانیشتنی",
    prescriptions: "ڕەچەتەکان",
    newPrescription: "ڕەچەتەی نوێ",
    drugName: "ناوی دەرمان",
    dose: "بڕ",
    frequency: "چەندبارەبوونەوە",
    form: "شێوە",
    medNotes: "تێبینی (ئارەزوومەندانە)",
    addMedication: "زیادکردنی دەرمان",
    addMasterDrug: "بەڕێوەبردنی دەرمانەکان",
    rxList: "لیستی ڕەچەتەکان",
    print: "چاپ",
    itemName: "ناوی ماددە",
    quantity: "ژمارە",
    addItem: "زیادکردنی ماددە",
    editItem: "دەستکاری ماددە",
    installApp: "دابەزاندنی بەرنامە",
    installDesc: "دابەزاندن بۆ ناو ئامێرەکەت",
    syncing: "هاوکاتکردن...",
    synced: "هاوکاتکرا",
    syncError: "هەڵە لە هاوکاتکردن",
    landingTitle: "Dentro",
    landingSubtitle: "چارەسەرێکی گشتگیر بۆ بەڕێوەبردنی کلینیکە مۆدێرنەکان",
    requestTrial: "داواکاری تاقیکردنەوە / بەشداریکردن",
    pricing: "پلانەکانی بەشداریکردن",
    filter: "فیلتەر",
    ageGroup: "تەمەن",
    under18: "کەمتر لە ١٨",
    from18to35: "١٨ - ٣٥",
    over35: "سەروو ٣٥",
    applyFilters: "جێبەجێکردن",
    clearFilters: "پاککردنەوە",
    status: "دۆخ",
    completed: "تەواو",
    noShow: "نەهات",
    none: "هیچ",
    existingPatient: "نەخۆشی تۆمارکراو",
    quickNewPatient: "کاتێکی نوێ",
    addAppointment: "زیادکردنی کات",
    description: "وەسف (ئارەزوومەندانە)",
    addToPatients: "زیادکردن بۆ نەخۆشەکان",
    convertGuestTitle: "گۆڕین بۆ نەخۆش",
    rxBgUrl: "بەستەری وێنەی ڕەچەتە (A5)",
    enterRxUrl: "بەستەرەکە لێرە بنووسە",
    uploadRxBg: "وێنەی باکگراوند",
    removeBg: "سڕینەوە",
    treatmentCost: "تێچووی چارەسەر",
    paymentReceived: "پارەی وەرگیراو",
    transactionHistory: "مێژووی پارەدان",
    receipt: "پسوڵە",
    printChromeWarning: "پێویستە چاپکردن لە ڕێگەی Chrome لەسەر کۆمپیوتەر ئەنجام بدرێت.",
    expenses: "خەرجییەکان",
    manageExpenses: "بەدواداچوون بۆ خەرجییەکانی ڕۆژانەی کلینیک",
    addExpense: "زیادکردنی خەرجی",
    editExpense: "دەستکاری خەرجی",
    price: "نرخ",
    total: "کۆی گشتی",
    totalExpenses: "کۆی خەرجییەکان",
    expenseDate: "بەرواری خەرج",
    deleteExpense: "سڕینەوەی خەرجی",
    deleteExpenseConfirm: "دەتەوێت ئەمە بسڕیتەوە؟",
    noExpenses: "هیچ خەرجییەک نییە بۆ ئەم ماوەیە.",
    manageMemos: "تێبینی و بیرخەرەوەکانانت بەڕێوە ببە",
    noMemos: "هیچ تێبینییەک نییە. کلیک لە زیادکردن بکە.",
    deleteMemo: "سڕینەوەی تێبینی",
    deleteMemoConfirm: "تێبینییەکە دەسڕێتەوە؟",
    managePurchases: "چاودێری ماددە و پێداویستییەکانی کلینیک بکە",
    action: "کردار",
    noItems: "هیچ ماددەیەکی لێنییە.",
    deleteItem: "ئەم ماددەیە لادەبەیت؟",
    registeredPatients: "نەخۆشی تۆمارکراو",
    noPatientsFilter: "هیچ نەخۆشێک نەدۆزرایەوە.",
    noPatientsCategory: "هیچ نەخۆشێک لەم جۆرە نییە.",
    contactWhatsapp: "پەیوەندی لە واتسئەپ",
    back: "گەڕانەوە",
    patientDetails: "وردەکاري نەخۆش",
    noMedicalHistory: "مێژووی پزیشکی تۆمارنەکراوە.",
    addNotesPlaceholder: "تێبینی لێرە بنووسە...",
    copyPhone: "کۆپیکردنی ژمارە",
    appointmentHistory: "مێژووی کاتەکان",
    noVisits: "هیچ سەردانێک تۆمارنەکراوە.",
    at: "لە",
    checkup: "پشكنين",
    deleteAppointment: "سڕینەوەی کات",
    deleteAppointmentConfirm: "ئەم کاتە دەسڕێتەوە؟",
    deleteRx: "سڕینەوەی ڕەچەتە",
    deleteRxConfirm: "ئەم تۆمارە دەسڕێتەوە؟",
    noRx: "هیچ ڕەچەتەیەک تۆمارنەکراوە.",
    rxPlaceholder: "ماددەکان لێرە دەردەکەون...",
    noTransactions: "هیچ مامەڵەیەک نییە.",
    thankYou: "سوپاس",
    dateLabel: "بەروار:",
    manageCalendar: "بەڕێوەبردنی کات و خشتەکان",
    noAppsDay: "هیچ کاتێک نییە بۆ ئەمڕۆ.",
    profile: "پڕۆفایل",
    markCompleted: "وەک تەواوبوو دیاریبکە",
    markNoShow: "وەک نەهاتوو دیاریبکە",
    resetStatus: "ڕێکخستنەوەی دۆخ",
    clinicDetails: "وردەکاری کلینیک",
    done: "تەواو",
    preferences: "هەڵبژاردەکان",
    bgImageSet: "وێنەی باکگراوند دیاریکراوە. بۆ گۆڕین, ئەمەی ئێستا لابدە.",
    recSize: "قەبارەی پێشنیارکراو: A5. جۆرەکان: JPG, PNG.",
    data: "داتا",
    cloudSync: "هاوکاتکردنی هەوری",
    fullNamePlaceholder: "ناوی تەواو",
    country: "وڵات",
    cityStreetPlaceholder: "شار، گەڕەک...",
    code: "کۆد",
    guestNamePlaceholder: "ناوی میوان",
    optionalNotesPlaceholder: "تێبینی ئارەزوومەندانە",
    egConsultation: "بۆ نموونە: ڕاوێژ",
    subscribe: "بەشداربە",
    fullAccess: "دەسەڵاتی تەواو",
    support: "٢٤/٧ پاڵپشتی",
    copyright: "© 2024 Dentro. هەموو مافەکان پارێزراون.",
    next: "دواتر",
    noDoctors: "هیچ پزیشکێک زیادنەکراوە.",
    drNamePlaceholder: "ناوی پزیشک",
    manageClinicSlogan: "بەڕێوەبردنی کلینیکەکەت بە زیرەكي و خێرایی.",
    editAppointment: "دەستکاری کات",
    date: "بەروار",
    clinicPhone: "ژمارەی کلینیک",
    printTicket: "چاپکردنی پسوڵە",
    appointmentTicket: "پسوڵەی کات",
    arriveEarlyNote: "تکایە ١٠ خولەک پێش کاتەکە ئامادەبە.",
    time: "کات",
    scheduled: "دیاریکراو",
    cancelled: "هەڵوەشایەوە",
    noshow: "نەهات",
    all: "هەموو",
    thirtyDays: "٣٠ ڕۆژ",
    selectGender: "ڕەگەز دیاریبکە",
    selectStatus: "دۆخ دیاریبکە",
    selectAge: "تەمەن دیاریبکە",
    startDate: "لە بەرواری",
    endDate: "بۆ بەرواری",
    textNote: "تێبینی نووسین",
    todoList: "لیستی کارەکان",
    addTodo: "کار زیادبکە",
    items: "دانەکان",
    materials: "ماددەکان",
    totalPurchases: "کۆی کڕینەکان",
    convertToExpense: "گەڕین بۆ خەرجی",
    confirmConvert: "ئەمە دەگۆڕیت بۆ خەرجی؟",
    dashboardTitle: "تەختەی کۆنترۆڵ و ئامارەکان",
    monthlyIncome: "داهاتی مانگانە",
    monthlyExpenses: "خەرجی مانگانە",
    netProfit: "قازانج",
    newPatientsThisMonth: "نەخۆشی نوێ",
    vsLastMonth: "بەراورد بە مانگی پێشوو",
    financialOverview: "پوختەی دارایی",
    appointmentStats: "ئاماری کاتەکان",
    genderDistribution: "دابەشبوونی ڕەگەز",
    recentActivity: "دواین چالاکیەکان",
    income: "داهات",
    profit: "قازانج",
    enableStats: "چالاککردنی ئامارەکان",
    disableStats: "ناچالاککردنی ئامارەکان",
    statsHidden: "ئامارەکان شاردراونەتەوە.",
    documents: "چاپکراوەکان",
    consentForm: "فۆرمی ڕەزامەندی",
    patientInstructions: "ڕێنمایی نەخۆش",
    paperSizeA4: "قەبارە: A4",
    paperSizeA5: "قەبارە: A5",
    addText: "زیادکردنی دەق",
    writeTextHere: "دەقەکە لێرە بنووسە بۆ چاپکردن...",
    documentText: "دەقی بەڵگەنامە",
    uploadBg: "باکگراوند",
    printDocument: "چاپ",
    alignRight: "ڕاست",
    alignCenter: "ناوەڕاست",
    alignLeft: "چەپ",
    fontSize: "قەبارەی نووسین",
    saveTemplate: "قاڵب هەڵگرە",
    loadTemplate: "قاڵب باربکە",
    templateName: "ناوی قاڵب",
    selectTemplate: "قاڵبێک دیاریبکە...",
    generalChart: "هێڵکاری گشتی",
    occlusalSurface: "ڕووی ددان",
    headChart: "سەر و دەموچاو",
    bodyChart: "لەش",
    front: "پێشەوە",
    backBody: "پشتەوە",
    labOrders: "داواکاری تاقیگە",
    manageLabOrders: "بەڕێوەبردنی داواکارییەکانی تاقیگە",
    newLabOrder: "داواکاری نوێ",
    labName: "ناوی تاقیگە",
    workType: "جۆری ئیش",
    toothCount: "ژمارەی ددان",
    toothNumbers: "ژمارەکانی ددان",
    shade: "ڕەنگ (Shade)",
    sentDate: "بەرواری ناردن",
    inProgress: "لە ژێر کاردایە",
    ready: "ئامادەیە",
    received: "وەرگیرا",
    selectLab: "تاقیگە هەڵبژێرە",
    addLab: "تاقیگە زیادبکە",
    enterLabName: "ناوی تاقیگە بنووسە",
    selectPatient: "نەخۆش دیاریبکە",
    editLabOrder: "دەستکاری داواکاری",
    sortBy: "ڕیزبەندی بەپێی",
    sortName: "ناو (A-Z)",
    sortNewest: "نوێترین",
    sortOldest: "کۆنترین",
    protectWithPin: "پاراستن بە کۆد",
    managePin: "بەڕێوەبردنی کۆد",
    enterPin: "کۆدەکە بنووسە (٦ ژمارە)",
    setPin: "کۆدی نوێ دابنێ",
    changePin: "گۆڕینی کۆد",
    removePin: "لادانی پاراستن",
    oldPin: "کۆدی کۆن",
    newPin: "کۆدی نوێ",
    pinSaved: "کۆد هەڵگیرا",
    pinRemoved: "پاراستن لادرا",
    wrongPin: "کۆدەکە هەڵەیە",
    labOrdersStats: "پوختەی داواکاری تاقیگە",
    totalLabOrders: "داواکاری چالاک",
    readyLabOrders: "ئامادە بۆ وەرگرتن",
    totalLabCost: "تێچووی تاقیگە",
    locked: "Locked",
    unlockToView: "کۆد بنووسە بۆ بینینی ئامارەکان",
    thisWeek: "ئەم هەفتەیە",
    last30Days: "٣٠ ڕۆژی ڕابردوو",
    vsYesterday: "بەراورد بە دوێنێ",
    vsLastWeek: "بەراورد بە هەفتەی ڕابردوو",
    vsPreviousPeriod: "بەراورد بە ماوەی پێشوو",
    addMedicalHistory: "زیادکردنی مێژووی پزیشکی",
    viewMedicalHistory: "بینینی مێژووی پزیشکی",
    addDentalHistory: "زیادکردنی مێژووی ددان",
    editDentalHistory: "دەستکاری مێژووی ددان",
    dentalHistory: "مێژووی ددان",
    brushingHabits: "خووی شوشتنی ددان",
    featuresTitle: "بۆچی DENTRO هەڵدەبژێریت؟",
    featuresSubtitle: "باشترین چارەسەر بۆ بەڕێوەبردنی کلینیکە مۆدێرنەکان",
    featurePatientMgmt: "بەڕێوەبردنی نەخۆش",
    featurePatientMgmtDesc: "فایلی ئەلیکترۆنی تەواو، مێژووی پزیشکی، و مێژووی ددان.",
    featureTeethChart: "هێڵکاری ددانی پێشکەوتوو",
    featureTeethChartDesc: "هێڵکاری پێشکەوتوو بۆ ددانی شیری و هەمیشەیی بە دیاریکردنی ڕووەکان و پلانی چارەسەری تەواو.",
    featureAppointments: "سیستەمی کاتەکان",
    featureAppointmentsDesc: "دیاریکردنی کات بە ئاسانی، کاتی خێرا بۆ میوانەکان و بەدواداچوونی دۆخەکان.",
    featureFinancials: "بەدواداچوونی دارایی",
    featureFinancialsDesc: "چاودێری داهات، خەرجی, قەرزی نەخۆش، و قیستەکان بە ڕاپۆرتی ورد.",
    featureLabOrders: "بەڕێوەبردنی تاقیگە",
    featureLabOrdersDesc: "چاودێری دۆخی داواکارییەکانی تاقیگە, تێچوون و ڕەنگەکان بۆ دڵنیابوون لە گەیشتن.",
    featureDocs: "بەڵگەنامە پڕۆفیشناڵەکان",
    featureDocsDesc: "چاپکردنی ڕەچەتە، پسوڵە، و فۆرمی ڕەزامەندی بە دیزاینی تایبەتمەندی خۆت.",
    featureDashboard: "تەختەی کۆنترۆڵ",
    featureDashboardDesc: "ئاماری راستەوخۆ لەسەر داهات و گەشەی نەخۆش و ئاستی کلینیک.",
    featureCloud: "هاوکاتکردنی هەوری",
    featureCloudDesc: "دەستگەیشتنێکی پارێزراو بۆ داتاکانت لە هەر ئامێرێک و لە هەر شوێنێک بێت.",
    featureMemos: "تێبینی و بیرخەرەوەکان",
    featureMemosDesc: "چاودێری ئەرکەکان، تێبینی کەسي، و لیستی کارەکان بکە.",
    featureInventory: "بەڕێوەبردنی کۆگا",
    featureInventoryDesc: "چاودێری پێداویستییەکانی کلینیک، تێچووی ماددەکان و کڕینەکان بکە.",
    featureUpdates: "نوێکاری بەردەوام",
    featureUpdatesDesc: "بەردەوام تایبەتمەندی نوێ و باشترکردن زیاد دەکەین بەپێی داواکارییەکانتان.",
    featureMore: "تایبەتمەندی زیاتر",
    featureMoreDesc: "زۆر تایبەتمەندی تر کە یارمەتیت دەدات بۆ ڕێکخستنی کلینیکەکەت.",
    featureMultiDoctor: "چەندین پزیشک",
    featureMultiDoctorDesc: "بەڕێوەبردنی چەندین پزیشك بە هەژمار و دەسەڵاتی جیاواز.",
    featureMultiDevice: "ئامێری جیاواز",
    featureMultiDeviceDesc: "دەستگەیشتن بە داتاکانی کلینیک لە مۆبایل، تابلێت، یان کۆمپیوتەر لە هەمان کاتدا.",
    featureProDesigns: "دیزاینی پرۆفیشناڵ",
    featureProDesignsDesc: "دیزاینی گونجاو و پرۆفیشناڵ بۆ ڕەچەتە و ڕاپۆرتەکان.",
    featureBackup: "پاڵپشتی و گەڕاندنەوە",
    featureBackupDesc: "فایلی پاڵپشتی (باکئەپ) پارێزراو بۆ هەموو داتاکانی کلینیکەکەت هەڵبگرە و هەر کاتێک ویستت بيگەڕێنەرەوە.",
    featureThemes: "ڕووکاری جیاواز",
    featureThemesDesc: "ڕەنگی ڕووکاری بەرنامەکە بگۆڕە بۆ ئەوەی لەگەڵ ئارەزووی خۆت بگونجێت.",
    featureMainAccount: "هەژماری سەرەکی کلینیک",
    featureMainAccountDesc: "کۆنترۆڵ تەواو بەسەر زانیارییەکانی کلینیک، پزیشکەکان و دەسەڵاتە کارگێڕییەکان.",
    featureDoctorProfile: "پرۆفایلي پزیشکی جیاواز",
    featureDoctorProfileDesc: "پرۆفایلی تاکەکەسی بۆ هەر پزیشکێک کە تەنها نەخۆشەکان و وردەکاري و ئامارەکانی خۆی تێدایە.",
    featureSecretaryAccount: "هەژماری سکرتێر",
    featureSecretaryAccountDesc: "هەژمارێکی تایبدت بۆ کارەکانی پێشوازی بە دەستڕاگەیشتنێکی سنووردار بە داتا داراییەکان.",
    bestValue: "باشترین نرخ",
    toothNote: "تێبینی",
    editToothNote: "دەستکاری تێبینی ددان",
    writeNoteHere: "تێبینی بنووسە...",
    textColor: "ڕەنگی نووسین",
    bgColor: "باکگراوند",
    titleFormat: "فۆرماتی ناونیشان",
    textFormat: "فۆرماتی نووسین",
    italic: "لار",
    textDir: "ئاڕاستەی نووسین",
  }
};
